# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This starts a local PostgreSQL DB.
  db:
    container_name: sales_db
    networks:
      - shared-network
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432